### ISSUE TITLE
About the bbox_mask

### ISSUE THREAD

**Issue by julingers** [joshi-bharat/deep_underwater_localization#12]
I found another problem that the code can't get right bbox_masks to filt x_, y_, conf_. You used predicted box to [get bbox_masks](https://github.com/joshi-bharat/deep_underwater_localization/blob/master/utils/misc_utils.py#L164-L209) in the computer graph.  Fist 'if bbox is None' can't be used, for the graph is statics. Second, input value bbox is tensor type，can't use 'for box in bbox' or ' // 'or 'int( )' and other gramma. And How to solve this problem? We need to use Tensor type to get bbox_masks from bbox in the computer graph.

**Comment by julingers** [comment]
@joshi-bharat I have solved the problem of bbox_mask. I just used numpy to implement the bboxmask filt in sess.run().

**Comment by julingers** [comment]
By the way, we can't use if-else  structure to define compute graph, but we can use it after sess.run().

**Comment by julingers** [comment]
@joshi-bharat I just found that it takes more inference time if use numpy. It's  more slower than before. So sad.

**Comment by joshi-bharat** [comment]
If the inference is done in the CPU, it should take the same amount of time. I will check this sometime.
