### ISSUE TITLE
 CycleGAN

### ISSUE THREAD

**Issue by zmj876902008** [joshi-bharat/deep_underwater_localization#2]
Hello, I want to know whether the  CycleGAN mentioned in the article is open source?

**Comment by joshi-bharat** [comment]
Yes CycleGAN is opensource. 
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix

**Comment by julingers** [comment]
> Hello, I want to know whether the CycleGAN mentioned in the article is open source?

Hi, I want to ask you whether you have run the source code successfully? I meet some problems and I run the code according to README.md. But I really don't know what the problem is. So I want to ask, have you run this source code successfully?  I expect for your reply. Thanks!
