### ISSUE TITLE
no refraction？

### ISSUE THREAD

**Issue by xiahaa** [joshi-bharat/deep_underwater_localization#9]
Hi, 
does refraction have some sorts of effects on the pose estimation?

**Comment by joshi-bharat** [comment]
Since the CNN predicts the relative position in terms of camera width and height, this position does not depend on camera intrinsics. It solely depends on the position of corners in the image. However, when doing PnP you should calibrate the cameras underwater, which should take care of refraction.

**Comment by xiahaa** [comment]
> Since the CNN predicts the relative position in terms of camera width and height, this position does not depend on camera intrinsics. It solely depends on the position of corners in the image. However, when doing PnP you should calibrate the cameras underwater, which should take care of refraction.

Thanks for your reply. 
May I ask are those underwater calibration images publicly available?

**Comment by joshi-bharat** [comment]
https://afrl.cse.sc.edu/afrl/resources/datasets/
